spring:
  profiles:
    active: development
---
spring:
  profiles: development
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:mysql:/.openec.zyhao.com:3306/employeedb
#    username: root
#    password: 3g2win.com
#    initialize: true
    url: jdbc:oracle:thin:@192.168.2.200:1521/orcl
    username: uniquecodedb
    password: 3g2win.com
    initialize: true
    validation-query: select * from dual
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
  zipkin:
    base-url: http://zipkin.openec.zyhao.com:9411/
security:
  ignored: /**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery.openec.zyhao.com:8761/eureka/
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://db.openec.zyhao.com:3306/dev
    username: root
    password: dbpass
    initialize: true
  zipkin:
      base-url: http://zipkin.openec.zyhao.com:9411/
security:
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:user.openec.zyhao.com}:8181/uaa/user
    client:
      client-id: acme
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery.openec.zyhao.com:8761/eureka/
---
spring:
  application:
    name: unique-code-service
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false
security:
  oauth2:
    resource:
      userInfoUri: http://user.openec.zyhao.com:8181/uaa/user
    client:
      client-id: acme
      access-token-uri: http://openec.zyhao.com:8787
