package com.zyhao.openec.uniquecode.entity;

import javax.persistence.Entity;
import javax.persistence.Id;
import java.io.Serializable;


/**
 * Model class of sequence_table.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity(name="sequence_table")
public class SequenceTable implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 序列名称. */
	@Id
	private String zyName;

	/** 当前值. */
	private Long zyCurrentValue;

	/** 增量值. */
	private Long zyIncrement;

	/**
	 * Constructor.
	 */
	public SequenceTable() {
	}

	public String getZyName() {
		return zyName;
	}

	public void setZyName(String zyName) {
		this.zyName = zyName;
	}

	public Long getZyCurrentValue() {
		return zyCurrentValue;
	}

	public void setZyCurrentValue(Long zyCurrentValue) {
		this.zyCurrentValue = zyCurrentValue;
	}

	public Long getZyIncrement() {
		return zyIncrement;
	}

	public void setZyIncrement(Long zyIncrement) {
		this.zyIncrement = zyIncrement;
	}
}
