package com.zyhao.openec.uniquecode.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;


/**
 * Model class of sequence_table.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity(name="sequence_table")
public class SequenceTable implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 序列名称. */
	@Id
	private String name;

	/** 当前值. */
	private Long currentValue;

	/** 增量值. */
	private Long increment;

	/**
	 * Constructor.
	 */
	public SequenceTable() {
	}

	/**
	 * Set the 序列名称.
	 * 
	 * @param name
	 *            序列名称
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the 序列名称.
	 * 
	 * @return 序列名称
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the 当前值.
	 * 
	 * @param currentValue
	 *            当前值
	 */
	public void setCurrentValue(Long currentValue) {
		this.currentValue = currentValue;
	}

	/**
	 * Get the 当前值.
	 * 
	 * @return 当前值
	 */
	public Long getCurrentValue() {
		return this.currentValue;
	}

	/**
	 * Set the 增量值.
	 * 
	 * @param increment
	 *            增量值
	 */
	public void setIncrement(Long increment) {
		this.increment = increment;
	}

	/**
	 * Get the 增量值.
	 * 
	 * @return 增量值
	 */
	public Long getIncrement() {
		return this.increment;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SequenceTable other = (SequenceTable) obj;
		if (name == null) {
			if (other.name != null) {
				return false;
			}
		} else if (!name.equals(other.name)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "SequenceTable [name=" + name + ", currentValue=" + currentValue + ", increment=" + increment + "]";
	}

}
