package com.zyhao.openec.uniquecode.entity;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Model class of unique_code.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity(name="unique_code")
public class UniqueCode implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** remote_ip. */
	@Id
	private String remoteIp;

	/** 唯一机器码. */
	private Long code;

	/**
	 * Constructor.
	 */
	public UniqueCode() {
	}

	/**
	 * Set the remote_ip.
	 * 
	 * @param remoteIp
	 *            remote_ip
	 */
	public void setRemoteIp(String remoteIp) {
		this.remoteIp = remoteIp;
	}

	/**
	 * Get the remote_ip.
	 * 
	 * @return remote_ip
	 */
	public String getRemoteIp() {
		return this.remoteIp;
	}

	/**
	 * Set the 唯一机器码.
	 * 
	 * @param code
	 *            唯一机器码
	 */
	public void setCode(Long code) {
		this.code = code;
	}

	/**
	 * Get the 唯一机器码.
	 * 
	 * @return 唯一机器码
	 */
	public Long getCode() {
		return this.code;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((remoteIp == null) ? 0 : remoteIp.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		UniqueCode other = (UniqueCode) obj;
		if (remoteIp == null) {
			if (other.remoteIp != null) {
				return false;
			}
		} else if (!remoteIp.equals(other.remoteIp)) {
			return false;
		}
		return true;
	}

}
